export enum Permission {
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  VIEW_RESTAURANTS = 'VIEW_RESTAURANTS',
  CREATE_RESTAURANT = 'CREATE_RESTAURANT',
  EDIT_RESTAURANT = 'EDIT_RESTAURANT',
  VIEW_ORDERS = 'VIEW_ORDERS',
  VIEW_MENU = 'VIEW_MENU',
  VIEW_BILLING = 'VIEW_BILLING',
  VIEW_INVENTORY = 'VIEW_INVENTORY',
}
